Modifying the search bar (base: project3)
BarneyShi/Team1-VanHouse pull request #15
Opened 2021-06-21 16:44 UTC by tyxxxx

Hi All,
Now. it looks like this:
![3](https://user-images.githubusercontent.com/43061724/122798181-26451400-d275-11eb-9096-da8412b700a7.jpg)
<img width="1237" alt="1" src="https://user-images.githubusercontent.com/43061724/122798192-28a76e00-d275-11eb-8b47-f99de5e55ac4.png">
![Uploading 2.jpg…]()

2021-06-21 19:26 UTC, BarneyShi requested changes

2021-06-21 19:26 UTC, BarneyShi commented on vanhouse/src/App.js
> +}
To keep style consistent, I think it's better to put css into a separate file. Same to other styles you made in component files.

2021-06-21 19:26 UTC, BarneyShi commented on vanhouse/src/App.js
> +            </InputGroup>
This might be put into <SeachBar />. As what we have in App.js now are top-level components.

2021-06-21 19:26 UTC, BarneyShi commented on vanhouse/src/components/Category.js
> +    const boxStyle = {
Make a css file.

2021-06-21 19:26 UTC, BarneyShi commented on vanhouse/src/components/PostDetail.js
> -    },
Did you pull the latest changes from project_3? These code are already in `project_3`, but you don't have them in your branch.

2021-06-24 19:02 UTC, BarneyShi commented on vanhouse/src/components/PostDetail.js
> -    },
@tyxxxx Here. You might need to merge or rebase your branch with your local `project_3`. Pull the newest changes to you local `project_3` before doing that.

2021-06-24 19:16 UTC, BarneyShi requested changes

2021-06-24 19:16 UTC, BarneyShi commented on vanhouse/src/App.js
> +
Here somehow they are not formatted. But in `project_3` branch now, they are formatted.

2021-06-24 19:16 UTC, BarneyShi commented on vanhouse/src/style.css
> +#table{
If you have the newest project_3, you'd see we have a `styles` folder. You might want to make a css file for each component you want to style and put styles there.

2021-06-25 00:26 UTC, NaithanB commented
I'm in the process of going through this now. An initial thought is that it looks like there is some formatting in the App.js file that should be cleaned up. I see big blocks of empty space. 

It also looks like the entire return statement is nearly duplicated several times in a series of if statements. It would be more readable to use the return statement from the project 3 branch and modify it to perform the logic inside you're doing to select the filters inside curly braces. E.g.
```
...
<Col lg={3} md={3}>
{
     (ul === 1 && <Price reset={(i)=>handleReset(i)}/>) || 
     (ul === 2 && <Location />)
...
}
</Col>
...
```
This way no code is duplicated. 

I could be wrong but I think the state name "ul" might be misleading since that refers to a standard html tag. Maybe something like "selectedFilter" or "selectedLeftDisplay" could work here?

An alternative solution could be to put the search filters in a subcomponent that is collapsible and sits beneath the searchbar. 

I noticed a lint error in the App.js file as well. There's an empty header on line 87.

I'll keep looking after dinner and let you know if I spot the source of the merge conflicts.

2021-06-25 01:26 UTC, NaithanB commented
Okay, I see one tricky integration problem. Initially the SearchBar was placed in the PostCollection component. I based some of the PostCollection and NewPost styling on this choice. Moving the SearchBar up into the main app component will break some of this. A quick fix to this would be just to pass the callback as a prop into the PostCollection component and keep the SearchBar there. Or, alternatively, keep the search filters in a collapsible subcomponent rather than keeping the filters as their own separate entities.

Another implementation detail we had talked about was saving the price and location inputs as states in the components. Has this been added anywhere?

I also noticed that there is a Category component that duplicates the Price and Location component code? Instead, just use both the Price and Location components where you would use the Category component. That way we reuse the code and reduce the complexity.

2021-06-25 01:36 UTC, NaithanB commented
I have a feeling that the other conflicting files could be from the project_3 branch diverging from the feature branch. Have you pulled the current project_3 branch and merged it into your branch since Tuesday?

2021-06-25 01:43 UTC, NaithanB commented
@tyxxxx, have you considered possibly using an accordion to store the new components? https://react-bootstrap.github.io/components/accordion/
That way we could have the filters hidden in the searchbar component itself and staying hidden until they're opened. It would mean that all the changes from your branch would stay in the SearchBar component and you would have a much lower chance of running into a merge conflict.

2021-06-25 01:52 UTC, BarneyShi commented
> @tyxxxx, have you considered possibly using an accordion to store the new components? https://react-bootstrap.github.io/components/accordion/
> That way we could have the filters hidden in the searchbar component itself and staying hidden until they're opened. It would mean that all the changes from your branch would stay in the SearchBar component and you would have a much lower chance of running into a merge conflict.

Second this. We can display filters under `SearchBar` once users click on something like a `Filter` button.

2021-07-19 01:25 UTC, closed without merging